services:
  db:
    container_name: mongodb
    image: mongo
  app:
    container_name: app
    build: .
    ports:
      - "8888:8888"
    environment:
      DB_HOST: mongodb://mongodb:27017
    depends_on:
      - "db"
    restart: unless-stopped
  bot:
    container_name: bot
    image: 11me/qr4funbot:1
    ports:
      - "8080:8080"
    environment:
      TG_TOKEN: "${TG_TOKEN}"
      WEB_HOOK: "${WEB_HOOK}"
      API_ENDPOINT: "${API_ENDPOINT}"
      LPORT: "${LPORT}"
      HANDLER_ENDPOINT: "${HANDLER_ENDPOINT}"
